"""
Integration & Regression Test Suite: Editor-Engine Compatibility Contract.

This test suite verifies that YAML adventure files generated by the adventure editor
can be successfully parsed, initialized, and played by the Python game engine.

Contract Under Test:
  Editor (Producer) -> YAML Data File -> Game Engine (Consumer)
"""

import os
import unittest
from pathlib import Path

try:
    import pytest
except ImportError:
    class _PytestMock:
        @staticmethod
        def raises(expected_exception, match=None):
            class _RaisesContext:
                def __enter__(self):
                    return self
                def __exit__(self, exc_type, exc_val, exc_tb):
                    if exc_type is None:
                        raise AssertionError(f"Expected {expected_exception.__name__} but no exception was raised.")
                    if not issubclass(exc_type, expected_exception):
                        return False
                    if match:
                        import re
                        if not re.search(match, str(exc_val)):
                            raise AssertionError(f"Exception message '{exc_val}' does not match pattern '{match}'")
                    return True
            return _RaisesContext()

        @staticmethod
        def skip(reason):
            raise unittest.SkipTest(reason)

    pytest = _PytestMock()

from game.gameObjects import Map, Item, Room, Fixture
from game.controller import Controller


TEST_ADVENTURE_PATH = "tests/test_adventure.yaml"


class TestEditorEngineContract(unittest.TestCase):
    """Verifies that editor-produced YAML schema matches engine consumption expectations."""

    def test_yaml_loads_and_schema_conforms(self):
        """Verify Map successfully loads editor YAML fields into domain objects."""
        game_map = Map(file_path=TEST_ADVENTURE_PATH)

        # 1. Intro & Win Screen metadata
        assert game_map.intro.get("title") == "Integration Test Manor"
        assert "quiet entry hall" in game_map.intro.get("text", "")
        assert "Type commands" in game_map.intro.get("instructions", "")
        assert game_map.win_screen.get("title") == "ADVENTURE COMPLETE"

        # 2. Player Starting Location
        assert game_map.starting_location == {"floor": 0, "x": 2, "y": 2}

        # 3. Starting Inventory
        assert len(game_map.player_start_invent) == 1
        assert game_map.player_start_invent[0].name == "pocket_flashlight"

        # 4. Item Definitions
        expected_items = {"pocket_flashlight", "brass_key", "ancient_relic"}
        assert expected_items.issubset(set(game_map.item_recipes.keys()))

        # 5. Room Definitions
        room_names = {r["name"] for r in game_map.room_recipes}
        assert "entry_hall" in room_names
        assert "courtyard" in room_names

        # 6. Grid Layout & Floor constraints (<= 6 floors)
        assert len(game_map.floor_recipes) == 1
        assert len(game_map.game_map) == 1
        # Floor 0: entry_hall at [2][2], courtyard at [1][2]
        assert game_map.game_map[0][2][2].name == "entry_hall"
        assert game_map.game_map[0][1][2].name == "courtyard"

        # 7. Win Conditions contract
        assert game_map.win_conditions == ["unlock_gate", "claim_relic"]

    def test_player_spawns_at_configured_location_with_inventory(self):
        """Verify Controller initializes player at editor's starting location with inventory."""
        ctrl = Controller(file_path=TEST_ADVENTURE_PATH)

        assert ctrl.player.level == 0
        assert ctrl.player.pos_x == 2
        assert ctrl.player.pos_y == 2

        current_room = ctrl.get_room()
        assert current_room is not False
        assert current_room.name == "entry_hall"

        inv_names = [item.name for item in ctrl.player.inventory]
        assert "pocket_flashlight" in inv_names

    def test_dynamic_room_description_assembly(self):
        """Verify base description, fixtures, room items, and trailing descriptions assemble properly."""
        ctrl = Controller(file_path=TEST_ADVENTURE_PATH)
        current_room = ctrl.get_room()

        desc = current_room.description

        # Base description
        assert "You stand in a vaulted entry hall" in desc
        # Active fixture description
        assert "carved stone pedestal" in desc
        # Placed item presence
        assert "An ornate brass key" in desc
        # Trailing navigation description
        assert "leads north toward the courtyard" in desc

    def test_player_item_pickup_interaction(self):
        """Verify picking up an item moves it from the room to player inventory."""
        ctrl = Controller(file_path=TEST_ADVENTURE_PATH)
        room = ctrl.get_room()

        # Item starts on the floor
        assert any(item.name == "brass_key" for item in room.inventory)

        # Execute pickup
        parsed = ctrl.parse_it("take brass key")
        ctrl.run_the_cmd(parsed)

        # Item now in inventory and removed from room
        player_inv = [item.name for item in ctrl.player.inventory]
        room_inv = [item.name for item in room.inventory]
        assert "brass_key" in player_inv
        assert "brass_key" not in room_inv

    def test_movement_and_grid_navigation(self):
        """Verify player moves according to exits and grid coordinates."""
        ctrl = Controller(file_path=TEST_ADVENTURE_PATH)
        assert ctrl.get_room().name == "entry_hall"

        parsed = ctrl.parse_it("go north")
        ctrl.run_the_cmd(parsed)

        new_room = ctrl.get_room()
        assert new_room.name == "courtyard"
        assert ctrl.player.pos_y == 1
        assert ctrl.player.pos_x == 2

    def test_event_trigger_and_world_mutations(self):
        """Verify using an item on a fixture triggers the event and mutates the world."""
        ctrl = Controller(file_path=TEST_ADVENTURE_PATH)

        # 1. Take the key in entry hall
        ctrl.run_the_cmd(ctrl.parse_it("take key"))
        assert any(i.name == "brass_key" for i in ctrl.player.inventory)

        # 2. Walk to courtyard
        ctrl.run_the_cmd(ctrl.parse_it("go north"))
        courtyard = ctrl.get_room()
        assert courtyard.name == "courtyard"

        # Gate fixture starts locked
        gate = courtyard.fixtures.get("heavy_gate")
        assert gate is not None
        assert gate.current_state == "locked"
        assert "north" in courtyard.locked_exits

        # 3. Use key on gate
        parsed = ctrl.parse_it("use key on gate")
        ctrl.run_the_cmd(parsed)

        # 4. Verify mutations
        assert "unlock_gate" in ctrl.player.completed_events
        assert gate.current_state == "unlocked"
        assert "north" not in courtyard.locked_exits

    def test_full_adventure_win_condition_flow(self):
        """Verify win condition logic: False initially, True once all win events complete."""
        ctrl = Controller(file_path=TEST_ADVENTURE_PATH)

        # Initially, win conditions are not met
        assert ctrl.events.check_win() is False

        # Step 1: Pick up key and move north
        ctrl.run_the_cmd(ctrl.parse_it("take key"))
        ctrl.run_the_cmd(ctrl.parse_it("go north"))

        # Step 2: Unlock gate (Event 1)
        ctrl.run_the_cmd(ctrl.parse_it("use key on gate"))
        assert "unlock_gate" in ctrl.player.completed_events
        # Still not won yet (claim_relic remains)
        assert ctrl.events.check_win() is False

        # Step 3: Take the relic (Event 2)
        ctrl.run_the_cmd(ctrl.parse_it("take relic"))
        assert "claim_relic" in ctrl.player.completed_events

        # Both win conditions complete -> Game won!
        assert ctrl.events.check_win() is True
        assert ctrl.room_info.get("GAME_WON") is True

    def test_empty_win_conditions_does_not_falsely_win(self):
        """Regression test: Empty win_conditions must not trigger vacuous victory."""
        ctrl = Controller(file_path=TEST_ADVENTURE_PATH)
        ctrl.map.win_conditions = []

        # Empty win condition list should return False, not True
        assert ctrl.events.check_win() is False

    def test_maximum_floor_limit_guardrail(self):
        """Verify engine rejects adventures defining more than 6 floors."""
        import tempfile
        import yaml

        with open(TEST_ADVENTURE_PATH, "r") as f:
            data = yaml.safe_load(f)

        # Add 7 floors
        empty_floor = [[None] * 5 for _ in range(5)]
        data["floors"] = [empty_floor for _ in range(7)]
        data["floors"][0][2][2] = "entry_hall"

        with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as tf:
            yaml.safe_dump(data, tf)
            tmp_name = tf.name

        try:
            with pytest.raises(ValueError, match="exceeds the maximum allowed 6 floors"):
                Map(file_path=tmp_name)
        finally:
            if os.path.exists(tmp_name):
                os.remove(tmp_name)

    def test_invalid_spawn_tile_guardrail(self):
        """Verify engine rejects adventures where player spawns on null tile or out of bounds."""
        import tempfile
        import yaml

        with open(TEST_ADVENTURE_PATH, "r") as f:
            data = yaml.safe_load(f)

        # Set spawn to empty tile [0, 0]
        data["player"]["starting_location"] = {"floor": 0, "x": 0, "y": 0}

        with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as tf:
            yaml.safe_dump(data, tf)
            tmp_name = tf.name

        try:
            with pytest.raises(ValueError, match="is empty \\(null\\) or out of bounds"):
                Map(file_path=tmp_name)
        finally:
            if os.path.exists(tmp_name):
                os.remove(tmp_name)

    def test_test_the_room_adventure_compatibility(self):
        """Verify the repository's canonical adventure data/test_the_room.yaml loads and runs."""
        test_the_room_path = "data/test_the_room.yaml"
        if not os.path.exists(test_the_room_path):
            pytest.skip("data/test_the_room.yaml not found")

        ctrl = Controller(file_path=test_the_room_path)
        current_room = ctrl.get_room()
        assert current_room is not False
        assert current_room.name == "specimen_vault"

        # Verify crystal resonator is in starting inventory
        inv_names = [i.name for i in ctrl.player.inventory]
        assert "crystal_resonator" in inv_names

        # Verify win conditions initially unmet
        assert ctrl.events.check_win() is False

        # Pull switch (Event 1)
        ctrl.run_the_cmd(ctrl.parse_it("pull switch"))
        assert "activate_vault_power" in ctrl.player.completed_events

        # Use crystal on pod (Event 2)
        ctrl.run_the_cmd(ctrl.parse_it("use crystal on pod"))
        assert "breach_specimen_pod" in ctrl.player.completed_events

        # Both win conditions satisfied
        assert ctrl.events.check_win() is True

    def test_editor_barebones_schema_compatibility(self):
        """
        Verify the exact schema generated by createBarebonesAdventure in schema.js
        loads into the engine and can be played to completion.
        """
        import tempfile
        import yaml

        barebones_data = {
            "intro": {
                "title": "A Simple Adventure",
                "text": "You find yourself in a quiet stone courtyard. The air is cool and still.",
                "instructions": "Type commands to move around and interact with the world."
            },
            "player": {
                "starting_location": {"floor": 0, "x": 2, "y": 2},
                "starting_inventory": []
            },
            "items": {
                "brass_key": {
                    "display_name": "Brass Key",
                    "presence": "An ornate brass key",
                    "keywords": ["key", "brass key"],
                    "aliases": ["key", "brass key"],
                    "states": {
                        "default": {
                            "description": "An ornate brass key with intricate scrollwork along the stem.",
                            "examine": "An ornate brass key with intricate scrollwork along the stem.",
                            "use": "Try using this key on a lock or door."
                        }
                    }
                }
            },
            "rooms": [
                {
                    "name": "entry_hall",
                    "display_name": "Grand Entry Hall",
                    "base_description": "You stand in a grand entry hall with towering stone arches.",
                    "fixtures": {
                        "pedestal": {
                            "display_name": "Stone Pedestal",
                            "priority": 10,
                            "state": "default",
                            "states": {
                                "default": "In the center of the room stands a carved stone pedestal."
                            },
                            "examine": {
                                "default": "A weathered stone pedestal carved from a single block of granite."
                            }
                        }
                    },
                    "trailing_description": "A wide doorway opens to the north.",
                    "items": ["brass_key"],
                    "exits": ["north"],
                    "locked_exits": []
                },
                {
                    "name": "courtyard",
                    "display_name": "Inner Courtyard",
                    "base_description": "An open courtyard open to the sky above.",
                    "fixtures": {
                        "heavy_gate": {
                            "display_name": "Heavy Iron Gate",
                            "priority": 10,
                            "state": "locked",
                            "states": {
                                "locked": "To the north, a heavy iron gate is secured with a massive padlock.",
                                "unlocked": "To the north, the heavy iron gate stands wide open."
                            },
                            "examine": {
                                "locked": "Sturdy iron bars that block passage north. A brass padlock holds them fast.",
                                "unlocked": "The gate hangs open, revealing a sunlit path beyond."
                            }
                        }
                    },
                    "trailing_description": "Arched exits lead south.",
                    "items": [],
                    "exits": ["south"],
                    "locked_exits": ["north"]
                }
            ],
            "floors": [
                [
                    [None, None, None, None, None],
                    [None, None, "courtyard", None, None],
                    [None, None, "entry_hall", None, None],
                    [None, None, None, None, None],
                    [None, None, None, None, None]
                ]
            ],
            "events": [
                {
                    "id": "unlock_gate",
                    "trigger": {
                        "type": "use_item",
                        "action": "use",
                        "source": "brass_key",
                        "target": "heavy_gate"
                    },
                    "conditions": [
                        {
                            "type": "in_room",
                            "room": "courtyard",
                            "fail_hint": "You need to be in the courtyard near the gate."
                        }
                    ],
                    "result": {
                        "set_fixture_state": [
                            {"room": "courtyard", "fixture": "heavy_gate", "state": "unlocked"}
                        ],
                        "open_exit": [
                            {"room": "courtyard", "direction": "north"}
                        ],
                        "message": "The key turns and the gate swings open!"
                    }
                }
            ],
            "win_conditions": ["unlock_gate"],
            "win_screen": {
                "title": "You Have Escaped!",
                "text": "You push past the iron gate and step into freedom."
            },
            "target_aliases": {
                "heavy_gate": ["gate", "padlock"],
                "pedestal": ["pedestal"]
            }
        }

        with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as tf:
            yaml.safe_dump(barebones_data, tf)
            tmp_path = tf.name

        try:
            ctrl = Controller(file_path=tmp_path)
            assert ctrl.get_room().name == "entry_hall"

            # Pick up key
            ctrl.run_the_cmd(ctrl.parse_it("take key"))
            assert any(i.name == "brass_key" for i in ctrl.player.inventory)

            # Move north to courtyard
            ctrl.run_the_cmd(ctrl.parse_it("go north"))
            assert ctrl.get_room().name == "courtyard"

            # Use key on gate -> triggers win
            ctrl.run_the_cmd(ctrl.parse_it("use key on gate"))
            assert "unlock_gate" in ctrl.player.completed_events
            assert ctrl.events.check_win() is True
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    def test_exits_dict_and_list_format_both_supported(self):
        """Verify engine supports both list exits ['north'] and dict exits {'north': 'room'}."""
        import tempfile
        import yaml

        with open(TEST_ADVENTURE_PATH, "r") as f:
            data = yaml.safe_load(f)

        # Change entry_hall exits to dict format
        for room in data["rooms"]:
            if room["name"] == "entry_hall":
                room["exits"] = {"north": "courtyard"}
            elif room["name"] == "courtyard":
                room["exits"] = ["south"]

        with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as tf:
            yaml.safe_dump(data, tf)
            tmp_path = tf.name

        try:
            ctrl = Controller(file_path=tmp_path)
            assert ctrl.get_room().name == "entry_hall"

            ctrl.run_the_cmd(ctrl.parse_it("go north"))
            assert ctrl.get_room().name == "courtyard"
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
